title: "פלטפורמת לימוד מסחר - תיעוד מוצר"
description: "Wireframes ו-PRDs לפלטפורמת לימוד מסחר במניות"

# GitHub Pages settings
theme: minima
lang: he
direction: rtl

# Markdown settings
markdown: kramdown
highlighter: rouge

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# RTL support
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: he
      dir: rtl

# Custom CSS for Hebrew/RTL support
sass:
  sass_dir: _sass
  style: compressed

# GitHub Pages specific settings
github: [metadata]
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Collections for better organization
collections:
  prds:
    output: true
    permalink: /:name/